### ISSUE TITLE
Fixing overlapping cards in index.html

### ISSUE THREAD

**Issue by rohitgulam** [rohitgulam/wall-of-opensource#21]
There are 3 profile cards that are overlapping with each other. Vaileth, Judith and Edson. They need to be fixed

**Comment by priyanshu6781** [comment]
Hey, I want to work. Please assign me!!

**Comment by priyanshu6781** [comment]
Hey @rohitgulam, it is done, please review.

- [x] overlapping of 3 profile cards fixed.
