### ISSUE TITLE
Profile Image not visible

### ISSUE THREAD

**Issue by priyanshu6781** [rohitgulam/wall-of-opensource#23]
### **These Issue needs to be fixed**

- [ ] Profile image of Gloria Mtagwaba not visible.
- [ ] Card icon of Vaileth Lawinot vissible

**Comment by rohitgulam** [comment]
Can you fix these? You can check where the image links go to and try getting the images from there

**Comment by priyanshu6781** [comment]
Yeah sure. I am working upon this.
