### ISSUE TITLE
Update README to state that new card must be added on the bottom, after the last current card. Not among existing cards

### ISSUE THREAD

**Issue by rohitgulam** [rohitgulam/wall-of-opensource#30]

**Comment by whiletrueee** [comment]
@rohitgulam i would like to work on this , can you assign this to me

**Comment by rohitgulam** [comment]
You can work on it now.

**Comment by rohitgulam** [comment]
Add that comment in number 4. where it says something like "4. Make changes in index.hmtl"

**Comment by whiletrueee** [comment]
@rohitgulam i have updated and created a pr please have a look on it

**Comment by whiletrueee** [comment]
@rohitgulam hey man! hello, i guess u haven't seen my pr so this is just a follow back to the previous comment.

**Comment by rohitgulam** [comment]
Thanks for pinging me.
